### ISSUE TITLE
ApphudDelegate build error for macOS app (Not catalyst)  ApphudSDK 3.0.1, Xcode 14.3

### ISSUE THREAD

**Issue by Panl** [apphud/ApphudSDK#96] opened 2023-04-15 15:44 UTC
Build errors:
<img width="300" alt="Screenshot 2023-04-15 at 11 40 01 PM" src="https://user-images.githubusercontent.com/3842675/232234833-181492bc-a7bc-459b-bf7a-d6bb33e2efea.png">

But my project settings:
<img width="600" alt="Screenshot 2023-04-15 at 11 40 15 PM" src="https://user-images.githubusercontent.com/3842675/232234849-182b8a4f-b494-49d8-b0b1-3afa408dcfcc.png">

**Comment by levochkaa** [comment] 2023-05-07 09:58
experiencing the same issue

**Comment by victormihaita** [comment] 2023-05-29 06:14
Same issue here. It looks like the problem is just on SPM

**Comment by Panl** [comment] 2023-05-29 06:24
https://github.com/Panl/ApphudSDK/commit/fe07e18107c00f6696df0f5bdc5b41ab62abc4e9 this commit fix this issue

**Comment by victormihaita** [comment] 2023-05-29 19:22
It would be nice to get that PR merged #97 so I won't have to fork this library.. @ren6 @vlr-code could you please try to update it?

**Comment by ren6** [comment] 2023-07-19 04:58
Merged, thank you! @victormihaita @Panl

**Closed by ren6** 2023-07-19 04:58 UTC
