### ISSUE TITLE
Crash on 3.5.3

### ISSUE THREAD

**Issue by andrey-krukovskiy** [apphud/ApphudSDK#123] opened 2024-10-26 11:27 UTC
<img width="506" alt="Снимок экрана 2024-10-26 в 14 23 59" src="https://github.com/user-attachments/assets/f721f1ca-84d0-4da1-9800-c3e6fef3fb36">

**Comment by ren6** [comment] 2024-10-28 14:16
Hello!
This is related to the following issue: 
Some apps built with Xcode 16 crashing on iOS 18 physical devices when using the `withCheckedContinuation` or `withCheckedThrowingContinuation` Swift continuations.

Steps to reproduce:

```
_ = await withCheckedContinuation { continuation in 
continuation.resume(returning: true) 
}
```
Since Apphud SDK also utilizes these Swift continuation methods, you may encounter crashes in one of our continuation lines as well. This issue is specific to Xcode 16, and if you experience the bug, a temporary workaround would be to build the app using Xcode 15.4.
Most likely, this bug appears to be only on devices, which are still on iOS 18 beta.

While some users have reported that this issue only occurs in Debug mode, others have encountered it in production App Store builds as well.

Be sure to keep an eye out for updates as this issue may be fixed in future Xcode 16 releases.

For more details, you can follow these links:

[Swift issue on GitHub](https://apphud.intercom-clicks.com/via/e?ob=aEo%2BJWuKAU6hPVb2qxEL5ubq%2FG3LcnW%2B%2F6U079sr%2FKsVXpqmGcxHEmr8u2BGFXLL&h=3cf6218ef97dd2d6b3f08bade827e3fcea27441c-xo2ecsjj_142434400177063&l=7690c8e83073db4b8ec7ae3036a04ec67cff8a7b-119492415)
[Apple Developer Forum thread](https://apphud.intercom-clicks.com/via/e?ob=w0fiblUfEr%2BvHrng3K6oIHwHk%2FO4qNuB%2BXa9%2BpVwZmqGXTLATpl0GgDn5VELAF7lROL9lROKF%2Bxv%2FCPgVHJw0Q%3D%3D&h=204c9afe45a8954f2eba79814f8caea90c586744-xo2ecsjj_142434400177063&l=8f92cc532c581245b48593364ee79847882eaa67-119492416)

**Closed** 2024-11-15 12:10 UTC
